import kotlin.String

/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
public object Libs {
    public const val activity_compose: String = "androidx.activity:activity-compose:_"

    public const val appcompat: String = "androidx.appcompat:appcompat:_"

    public const val animation: String = "androidx.compose.animation:animation:_"

    public const val androidx_compose_compiler_compiler: String =
            "androidx.compose.compiler:compiler:_"

    public const val androidx_compose_material_material: String =
            "androidx.compose.material:material:_"

    public const val ui_tooling: String = "androidx.compose.ui:ui-tooling:_"

    public const val constraintlayout: String = "androidx.constraintlayout:constraintlayout:_"

    public const val core_ktx: String = "androidx.core:core-ktx:_"

    public const val databinding_adapters: String = "androidx.databinding:databinding-adapters:_"

    public const val databinding_common: String = "androidx.databinding:databinding-common:_"

    public const val databinding_compiler: String = "androidx.databinding:databinding-compiler:_"

    public const val databinding_ktx: String = "androidx.databinding:databinding-ktx:_"

    public const val databinding_runtime: String = "androidx.databinding:databinding-runtime:_"

    public const val viewbinding: String = "androidx.databinding:viewbinding:_"

    public const val fragment: String = "androidx.fragment:fragment:_"

    public const val fragment_ktx: String = "androidx.fragment:fragment-ktx:_"

    public const val lifecycle_viewmodel_compose: String =
            "androidx.lifecycle:lifecycle-viewmodel-compose:_"

    public const val lifecycle_viewmodel_ktx: String =
            "androidx.lifecycle:lifecycle-viewmodel-ktx:_"

    public const val multidex: String = "androidx.multidex:multidex:_"

    public const val navigation_fragment_ktx: String =
            "androidx.navigation:navigation-fragment-ktx:_"

    public const val navigation_safe_args_gradle_plugin: String =
            "androidx.navigation:navigation-safe-args-gradle-plugin:_"

    public const val navigation_ui_ktx: String = "androidx.navigation:navigation-ui-ktx:_"

    public const val recyclerview: String = "androidx.recyclerview:recyclerview:_"

    public const val turbine: String = "app.cash.turbine:turbine:_"

    public const val kermit: String = "co.touchlab:kermit:_"

    public const val redux_kotlin_threadsafe: String = "com.1gravity:redux-kotlin-threadsafe:_"

    public const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:_"

    public const val instance_keeper: String = "com.arkivanov.essenty:instance-keeper:_"

    public const val lifecycle: String = "com.arkivanov.essenty:lifecycle:_"

    public const val parcelable: String = "com.arkivanov.essenty:parcelable:_"

    public const val reaktive: String = "com.badoo.reaktive:reaktive:_"

    public const val uuid: String = "com.benasher44:uuid:_"

    public const val glide: String = "com.github.bumptech.glide:glide:_"

    public const val groupie: String = "com.github.lisawray.groupie:groupie:_"

    public const val groupie_viewbinding: String =
            "com.github.lisawray.groupie:groupie-viewbinding:_"

    public const val landscapist_glide: String = "com.github.skydoves:landscapist-glide:_"

    public const val com_google_android_material_material: String =
            "com.google.android.material:material:_"

    public const val bignum: String = "com.ionspin.kotlin:bignum:_"

    public const val kotlin_result: String = "com.michael-bull.kotlin-result:kotlin-result:_"

    public const val kotlin_result_coroutines: String =
            "com.michael-bull.kotlin-result:kotlin-result-coroutines:_"

    public const val android_driver: String = "com.squareup.sqldelight:android-driver:_"

    public const val coroutines_extensions: String =
            "com.squareup.sqldelight:coroutines-extensions:_"

    public const val gradle_plugin: String = "com.squareup.sqldelight:gradle-plugin:_"

    public const val native_driver: String = "com.squareup.sqldelight:native-driver:_"

    public const val com_squareup_sqldelight_runtime: String = "com.squareup.sqldelight:runtime:_"

    public const val de_fayard_buildsrclibs_gradle_plugin: String =
            "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    public const val koin_android: String = "io.insert-koin:koin-android:_"

    public const val koin_core: String = "io.insert-koin:koin-core:_"

    public const val kotest_runner_junit5: String = "io.kotest:kotest-runner-junit5:_"

    public const val ktor_client_cio: String = "io.ktor:ktor-client-cio:_"

    public const val ktor_client_content_negotiation: String =
            "io.ktor:ktor-client-content-negotiation:_"

    public const val ktor_client_core: String = "io.ktor:ktor-client-core:_"

    public const val ktor_client_ios: String = "io.ktor:ktor-client-ios:_"

    public const val ktor_client_json: String = "io.ktor:ktor-client-json:_"

    public const val ktor_client_logging: String = "io.ktor:ktor-client-logging:_"

    public const val ktor_client_serialization: String = "io.ktor:ktor-client-serialization:_"

    public const val ktor_serialization_kotlinx_json: String =
            "io.ktor:ktor-serialization-kotlinx-json:_"

    public const val mockk: String = "io.mockk:mockk:_"

    public const val junit: String = "junit:junit:_"

    public const val org_barfuin_gradle_taskinfo_gradle_plugin: String =
            "org.barfuin.gradle.taskinfo:org.barfuin.gradle.taskinfo.gradle.plugin:_"

    public const val org_jacoco_ant: String = "org.jacoco:org.jacoco.ant:_"

    public const val org_jetbrains_compose_compiler_compiler: String =
            "org.jetbrains.compose.compiler:compiler:_"

    public const val compose_gradle_plugin: String = "org.jetbrains.compose:compose-gradle-plugin:_"

    public const val all_modules_page_plugin: String =
            "org.jetbrains.dokka:all-modules-page-plugin:_"

    public const val dokka_base: String = "org.jetbrains.dokka:dokka-base:_"

    public const val gfm_template_processing_plugin: String =
            "org.jetbrains.dokka:gfm-template-processing-plugin:_"

    public const val jekyll_template_processing_plugin: String =
            "org.jetbrains.dokka:jekyll-template-processing-plugin:_"

    public const val org_jetbrains_dokka_gradle_plugin: String =
            "org.jetbrains.dokka:org.jetbrains.dokka.gradle.plugin:_"

    public const val org_jetbrains_kotlin_plugin_serialization_gradle_plugin: String =
            "org.jetbrains.kotlin.plugin.serialization:org.jetbrains.kotlin.plugin.serialization.gradle.plugin:_"

    public const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    public const val kotlin_parcelize_compiler: String =
            "org.jetbrains.kotlin:kotlin-parcelize-compiler:_"

    public const val kotlin_parcelize_runtime: String =
            "org.jetbrains.kotlin:kotlin-parcelize-runtime:_"

    public const val kotlin_reflect: String = "org.jetbrains.kotlin:kotlin-reflect:_"

    public const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:_"

    public const val kotlin_serialization: String = "org.jetbrains.kotlin:kotlin-serialization:_"

    public const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:_"

    public const val kotlin_test: String = "org.jetbrains.kotlin:kotlin-test"

    public const val kotlinx_coroutines_android: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-android:_"

    public const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:_"

    public const val kotlinx_coroutines_test: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-test:_"

    public const val kotlinx_datetime: String = "org.jetbrains.kotlinx:kotlinx-datetime:_"
}
