name: Create documentation (Dokka / Docusaurus)

on:
  workflow_dispatch:
  push:
    branches:
      - documentation
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Create Dokka documentation
        run: ./gradlew dokkaHtmlMultiModule

      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
          cache-dependency-path: website/yarn.lock

      - name: Install dependencies
        run: |
          cd website
          yarn install --frozen-lockfile

      - name: Build website
        run: |
          cd website
          yarn build

      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./website/build/
