name: Run lint and tests

on:
  push:
    branches:
      - feature/**
  pull_request:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.3.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Run Lint
        run: ./gradlew lint

      - name: Test results
        uses: actions/upload-artifact@v2
        with:
          name: unit-tests-results
          path: bloc-core/build/reports/tests/testReleaseUnitTest/index.html

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.3.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Run Tests
        run: ./gradlew test
