name: Run lint and tests

on:
  workflow_dispatch:
  push:
    branches:
      - feature/**
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.3.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Run Lint
        run: ./gradlew lint

  detekt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.3.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Run Detekt
        run: ./gradlew detekt

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.3.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Run Tests
        run: ./gradlew test

      - name: Test results Debug
        uses: actions/upload-artifact@v2
        with:
          name: debug-unit-tests-results
          path: bloc-core/build/reports/tests/testDebugUnitTest/

      - name: Test results Release
        uses: actions/upload-artifact@v2
        with:
          name: release-unit-tests-results
          path: bloc-core/build/reports/tests/testReleaseUnitTest/

