name: Publish snapshot

on:
  push:
    branches: [ master, feature/*, kotlin-* ]
  pull_request:
    branches: [ master ]

jobs:
  publish-snapshot:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Publish Snapshot
        env:
          SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
          SNAPSHOT: 'TRUE'
        run: ./gradlew publish

      - name: Archive bloc-core publications dir
        uses: actions/upload-artifact@v1
        with:
          name: publications-${{ matrix.os }}
          path: bloc-core/build/publications

      - name: Archive bloc-redux publications dir
        uses: actions/upload-artifact@v1
        with:
          name: publications-${{ matrix.os }}
          path: bloc-redux/build/publications

      - name: Archive bloc-compose dir
        uses: actions/upload-artifact@v1
        with:
          name: publications-${{ matrix.os }}
          path: bloc-compose/build/publications
