name: Publish snapshot

on:
  push:
    branches:
      - master

env:
  SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
  SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
  GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
  GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.3.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Run Lint
        run: ./gradlew lint

  detekt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.3.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Run Detekt
        run: ./gradlew detekt

  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.3.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Run Tests
        run: ./gradlew test

      - name: Test results Debug
        uses: actions/upload-artifact@v2
        with:
          name: debug-unit-tests-results
          path: bloc-core/build/reports/tests/testDebugUnitTest/

      - name: Test results Release
        uses: actions/upload-artifact@v2
        with:
          name: release-unit-tests-results
          path: bloc-core/build/reports/tests/testReleaseUnitTest/

  publish-snapshot:
    needs: [lint, detekt, tests]

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.3.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Publish Snapshot
        run: ./gradlew -Dorg.gradle.parallel=false publish -PPUBLISH_AS_SNAPSHOT=true
