name: Publish snapshot

on:
  push:
    branches: [ master ]

env:
  SONATYPE_NEXUS_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
  SONATYPE_NEXUS_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
  GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
  GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
  PUBLISH_AS_SNAPSHOT: true

jobs:
  publish-snapshot:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.3.0
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Publish Snapshot
        run: ./gradlew publish
